### ISSUE TITLE
NVA协议投屏失败

### ISSUE THREAD

**Issue by jleaves** [xfangfang/Macast-plugins#20]
遇到了类似 #19  的问题。安卓的Bilibili投屏到Windows的macast.exe，调用NVA协议失败。

Macast是0.7版本，NVA插件已更新到0.32版本。

附日志

```
[02/Jul/2024:16:06:28] ENGINE Listening for SIGTERM.
[02/Jul/2024:16:06:28] ENGINE Bus STARTING
[02/Jul/2024:16:06:28] ENGINE Serving on http://0.0.0.0:18707
[02/Jul/2024:16:06:28] ENGINE Set handler for console events.
[02/Jul/2024:16:06:28] ENGINE Started monitor thread 'Autoreloader'.
[02/Jul/2024:16:06:28] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
[02/Jul/2024:16:06:28] ENGINE Bus STARTED
192.168.31.167 - - [02/Jul/2024:16:06:32] "GET /description.xml HTTP/1.1" 200 2759 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.31.167 - - [02/Jul/2024:16:06:32] "GET /dlna/AVTransport.xml HTTP/1.1" 200 21114 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.31.167 - - [02/Jul/2024:16:06:32] "GET /dlna/RenderingControl.xml HTTP/1.1" 200 8536 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.31.167 - - [02/Jul/2024:16:06:32] "GET /dlna/NirvanaControl.xml HTTP/1.1" 200 5850 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.31.167 - - [02/Jul/2024:16:06:55] "SETUP /projection HTTP/1.0" 200 - "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
192.168.31.167 - - [02/Jul/2024:16:06:55] "POST /NirvanaControl/action HTTP/1.1" 200 412 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"
[02/Jul/2024:16:06:55] ENGINE Error in 'renderer_av_uri' listener <bound method Macast.renderer_av_uri of <macast.macast.Macast object at 0x0000014081D9DBC8>>
Traceback (most recent call last):
  File "cherrypy\process\wspbus.py", line 230, in publish
  File "macast\macast.py", line 424, in renderer_av_uri
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by xfangfang** [comment]
这个应该是API失效了，我注意到BBDOWN也遇到了类似的问题：https://github.com/nilaoda/BBDown/issues/901

这个问题如果要修复的话，有两个方案：
1. 找到新的投屏接口，我使用一个未登陆账号的安卓客户端确实可以向非官方DLNA接收器进行投屏，说明肯定有接口可以实现投放没有跨域限制的视频链接，需要有人花时间找到这样的接口。
2. 更新Macast本体，使其可以接受dash链接（视频音频分离）

我其实感觉对于Macast来说第二个方案最好，因为这可以保证高清视频的投放，但是选择这个意味着 插件间会存在不兼容，比如nva插件搭配不支持dash的potplayer插件就无法投屏了，所以最好是可以两个方案都选择。

但是这个显然是比较花时间的，我暂时没有时间来完善这个应用了。

---

顺便一提，欢迎为这个项目捐助，我会尽量找出来时间更新的：

<image width="300" src="https://xfangfang.github.io/Macast/sponsorships.png" />

**Comment by xfangfang** [comment]
简单完成了前面的方案1，顺便修复了一下直播无法投屏的问题，更新插件到 0.33 应该就可以了。

**Comment by jleaves** [comment]
NVA插件更新后，Bilibili又可以在NVA模式下顺利投屏了。感谢火速更新！

**Comment by jleaves** [comment]
那我就先关闭这个issue了
